modLoader="javafml"
loaderVersion="[40,)"
license="Apache License version 2.0"

[[mods]]
modId="valleyman_beans"
version="4.9.0"
displayName="valleyman beans"
credits="floi"
displayURL="https://www.curseforge.com/minecraft/search?page=1&pageSize=20&sortType=1&class=mc-mods"
logoFile="logo.png"
authors="Floi"
description='''
beans
'''

[[dependencies.valleyman_beans]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"




